package ups.prueba;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2022-02-01T11:59:43.789-05:00
 * Generated source version: 2.7.11
 * 
 */
@WebServiceClient(name = "ObraServicesService", 
                  wsdlLocation = "http://localhost:8080/EVAMendezBryanSRV/ObraServices?wsdl",
                  targetNamespace = "http://services.EVAMendezBryanSRV.prueba.ups/") 
public class ObraServicesService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://services.EVAMendezBryanSRV.prueba.ups/", "ObraServicesService");
    public final static QName ObraServicesPort = new QName("http://services.EVAMendezBryanSRV.prueba.ups/", "ObraServicesPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/EVAMendezBryanSRV/ObraServices?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ObraServicesService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/EVAMendezBryanSRV/ObraServices?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ObraServicesService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ObraServicesService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ObraServicesService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ObraServicesService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ObraServicesService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ObraServicesService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ObraServices
     */
    @WebEndpoint(name = "ObraServicesPort")
    public ObraServices getObraServicesPort() {
        return super.getPort(ObraServicesPort, ObraServices.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ObraServices
     */
    @WebEndpoint(name = "ObraServicesPort")
    public ObraServices getObraServicesPort(WebServiceFeature... features) {
        return super.getPort(ObraServicesPort, ObraServices.class, features);
    }

}
