
package ups.prueba;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2022-02-01T11:59:43.702-05:00
 * Generated source version: 2.7.11
 * 
 */
public final class ObraServices_ObraServicesPort_Client {

    private static final QName SERVICE_NAME = new QName("http://services.EVAMendezBryanSRV.prueba.ups/", "ObraServicesService");

    public ObraServices_ObraServicesPort_Client() {
    }

    public void insertarObras(String args[]) throws java.lang.Exception {
    	URL wsdlURL = ObraServicesService.WSDL_LOCATION;
    	if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
    	
    	
    	ObraServicesService ss = new ObraServicesService(wsdlURL, SERVICE_NAME);
        ObraServices port = ss.getObraServicesPort();
        ups.prueba.Obra obra = new Obra();
        obra.setCodigo(2);
        obra.setAutor("Donatelo");
        obra.setNombre("Mona Lisa");
        obra.setTipo("Pinturistica");
        obra.setFecha("05/24/1785");
        java.lang.String _insertarObra__return = port.insertarObra(obra);
        System.out.println("Verificacion=" + _insertarObra__return);
    	
    }
    }
    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ObraServicesService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        
        ObraServicesService ss = new ObraServicesService(wsdlURL, SERVICE_NAME);
        ObraServices port = ss.getObraServicesPort();  
        
        {
        System.out.println("Invoking obtenerObras...");
        java.util.List<ups.prueba.Obra> _obtenerObras__return = port.obtenerObras();
        
        System.out.println("obtenerObras.result=" + _obtenerObras__return);


        }
       
        {
        System.out.println("Invoking insertarObra...");
        ups.prueba.Obra obra = new Obra();
        obra.setCodigo(3);
        obra.setAutor("Donatelo");
        obra.setNombre("Mona Lisa");
        obra.setTipo("Pinturistica");
        obra.setFecha("05/24/1785");
        java.lang.String _insertarObra__return = port.insertarObra(obra);
        System.out.println("Verificacion=" + _insertarObra__return);


        }
     

        System.exit(0);
    }

}
