package ups.prueba;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2022-02-01T11:59:43.776-05:00
 * Generated source version: 2.7.11
 * 
 */
@WebService(targetNamespace = "http://services.EVAMendezBryanSRV.prueba.ups/", name = "ObraServices")
@XmlSeeAlso({ObjectFactory.class})
public interface ObraServices {

    @WebMethod
    @RequestWrapper(localName = "obtenerObras", targetNamespace = "http://services.EVAMendezBryanSRV.prueba.ups/", className = "ups.prueba.ObtenerObras")
    @ResponseWrapper(localName = "obtenerObrasResponse", targetNamespace = "http://services.EVAMendezBryanSRV.prueba.ups/", className = "ups.prueba.ObtenerObrasResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ups.prueba.Obra> obtenerObras();

    @WebMethod
    @RequestWrapper(localName = "insertarObra", targetNamespace = "http://services.EVAMendezBryanSRV.prueba.ups/", className = "ups.prueba.InsertarObra")
    @ResponseWrapper(localName = "insertarObraResponse", targetNamespace = "http://services.EVAMendezBryanSRV.prueba.ups/", className = "ups.prueba.InsertarObraResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String insertarObra(
        @WebParam(name = "arg0", targetNamespace = "")
        ups.prueba.Obra arg0
    );
}
